### ISSUE TITLE
typeorm 0.3x compatibility

### ISSUE THREAD

**Issue by gpproton** [slaviqueue/typeorm-pg-adjacency-list-tree#1]
Hi, i'm currently considering using this package in my project but kept receiving a dependency error concerning of typeorm 0.2 i would appreciate any recommendation to solve this.

**Comment by slaviqueue** [comment]
@gpproton 
Wow, seems like I've missed a major typeorm update. 0.3.x looks pretty buggy as for me right now. Anyway I'm working on migrating to 0.3, but I need [this one](https://github.com/typeorm/typeorm/issues/8939) to be fixed in the next typeorm patch to deploy an update.

**Comment by gpproton** [comment]
Thanks, it would be a life safer.
